# Generated by Django 4.1.5 on 2023-01-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='my_library.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='my_library.category'),
        ),
    ]
