# Generated by Django 4.0.4 on 2023-01-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0004_remove_book_author_book_author_remove_book_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_published',
        ),
    ]
